# Generated by Django 3.0 on 2021-08-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurencecompanyapp', '0001_initial'),
        ('hospital', '0002_auto_20210818_0833'),
        ('patient', '0003_auto_20210818_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_status_code', models.CharField(max_length=90)),
                ('status_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_number', models.IntegerField(primary_key=True, serialize=False)),
                ('detailes', models.TextField()),
                ('Claim_datees', models.DateField()),
                ('claim_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claimsapp.ClaimStatus')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurencecompanyapp.Company')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospitals')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
