# Generated by Django 3.0 on 2021-08-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210815_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'PATIENT INFORMATION '},
        ),
    ]
