# Generated by Django 3.0 on 2021-08-18 18:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/user')),
                ('biodata', models.TextField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'FEMALE'), ('M', 'MALE'), ('OTHERS', 'OTHER CATEGERY')], max_length=20, null=True)),
                ('BirthDay', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
