# Generated by Django 3.0 on 2021-08-11 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField()),
                ('htype', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=300)),
                ('address', models.TextField()),
                ('updateDate', models.DateField(default=datetime.datetime.now)),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital_Type')),
            ],
        ),
    ]
