# Generated by Django 3.0 on 2021-08-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitals',
            options={'verbose_name_plural': 'HOSPITAL INFO '},
        ),
    ]
